structure Animals :> ANIMALS = struct

  val animals =
    [ "aardvark"
    , "ant"
    , "ape"
    , "armadillo"
    , "asp"
    , "auk"
    , "badger"
    , "bat"
    , "bear"
    , "bee"
    , "bird"
    , "blackbird"
    , "boa"
    , "boar"
    , "buffalo"
    , "buzzard"
    , "calf"
    , "cat"
    , "cheetah"
    , "chimp"
    , "cod"
    , "condor"
    , "cougar"
    , "cow"
    , "coyote"
    , "cub"
    , "deer"
    , "doe"
    , "dog"
    , "dolphin"
    , "duck"
    , "eagle"
    , "eel"
    , "eft"
    , "elephant"
    , "elk"
    , "emu"
    , "ewe"
    , "falcon"
    , "ferret"
    , "flamingo"
    , "fox"
    , "frog "
    , "gibbon"
    , "giraffe"
    , "gnu"
    , "goat"
    , "goldfinch"
    , "goose"
    , "gorilla"
    , "hawk"
    , "hen"
    , "hippo"
    , "hog"
    , "hyena"
    , "jay"
    , "kestrel"
    , "kit"
    , "koala"
    , "lark"
    , "lion"
    , "loon"
    , "lynx"
    , "macaw"
    , "mallard"
    , "mole"
    , "monkey"
    , "moose"
    , "nit"
    , "orangutan"
    , "osprey"
    , "ostrich"
    , "owl"
    , "ox"
    , "panda"
    , "parrot"
    , "penguin"
    , "pig"
    , "puffin"
    , "pup"
    , "rabbit"
    , "ram"
    , "rat"
    , "rhino"
    , "robin"
    , "seal"
    , "sloth"
    , "sow"
    , "swan"
    , "toad"
    , "tiger"
    , "vulture"
    , "whale"
    , "wolf "
    , "yak"
    ]

    val special = "zebra"

    fun compare (a1, a2) =
      case Int.compare (size a1, size a2)
        of EQUAL => String.compare (a1, a2)
         | order => order

    fun insert (x, []) = [x]
      | insert (x, y::ys) =
        case compare (x, y) of GREATER => y :: insert(x, ys)
                             | _       => x :: y :: ys

    val animals = Vector.fromList (foldl insert [] animals)
end
